# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
user = User.new(id: 0, name: "Anonymous User", email: "Anon@Anon", password: SecureRandom.hex(16))
user.reset_session_token!
user.save!


Cat.create(name: "geometry")  #1
Cat.create(name: "algebra")  #2
Cat.create(name: "probability") #3
Cat.create(name: "numerical")  #4
Cat.create(name: "analysis")  #5




item = Item.create(title: "A Guided Tour of Mathematical Methods: For the Physical Sciences Edition 2", price: 60.00, img: "http://img1.imagesbn.com/p/9780521542616_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0521542618", published: "April 2009", publisher: "Cambridge University Press", author: "Roel Snieder", overview: "
In contrast to traditional textbooks for students and professionals in the physical sciences, this book presents its material in the form of problems. The second edition contains new chapters on dimensional analysis, variational calculus, and the asymptotic evaluation of integrals. The book can be used by undergraduates and lower-level graduate students. It can serve as a stand-alone text, or as a source of problems and examples to complement other textbooks. First Edition Hb (2001): 0-521-78241-4 First Edition Pb (2001): 0-521-78751-3
")

item = Item.create(title: "Fractals and Scaling in Finance: Discontinuity, Concentration, Risk. Selecta Volume E Edition 1", price: 99.00, img: "http://img2.imagesbn.com/p/9780387983639_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0387983635", published: "September 1997", publisher: "Springer New York", author: "Benoit B. Mandelbrot,R.E. Gomory (Foreword )", overview: "
Mandelbrot is world famous for his creation of the new mathematics of fractal geometry. Yet few people know that his original field of applied research was in econometrics and financial models, applying ideas of scaling and self-similarity to arrays of data generated by financial analyses. This book brings together his original papers as well as many original chapters specifically written for this book.
")
item = Item.create(title: "Random Phenomena: Fundamentals of Probability and Statistics for Engineers Edition 1", price: 154.95, img: "http://img2.imagesbn.com/p/9781420044973_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1420044974", published: "September 2009", publisher: "CRC Press", author: "Babatunde A. Ogunnaike", overview: "
Many of the problems that engineers face involve randomly varying phenomena of one sort or another. However, if characterized properly, even such randomness and the resulting uncertainty are subject to rigorous mathematical analysis.
Taking into account the uniquely multidisciplinary demands of 21st-century science and engineering, Random Phenomena: Fundamentals of Probability and Statistics for Engineers provides students with a working knowledge of how to solve engineering problems that involve randomly varying phenomena. Basing his approach on the principle of theoretical foundations before application, Dr. Ogunnaike presents a classroom-tested course of study that explains how to master and use probability and statistics appropriately to deal with uncertainty in standard problems and those that are new and unfamiliar.
Giving students the tools and confidence to formulate practical solutions to problems, this book offers many useful features, including:
Unique case studies to illustrate the fundamentals and applications of probability and foster understanding of the random variable and its distribution
Examples of development, selection, and analysis of probability models for specific random variables
Presentation of core concepts and ideas behind statistics and design of experiments
Selected \"special topics,\" including reliability and life testing, quality assurance and control, and multivariate analysis
As classic scientific boundaries continue to be restructured, the use of engineering is spilling over into more non-traditional areas, ranging from molecular biology to finance. This book emphasizes fundamentals and a \"first principles\" approach to deal with this evolution. It illustrates theory with practical examples and case studies, equipping readers to deal with a wide range of problems beyond those in the book.
About the Author:Professor Ogunnaike is Interim Dean of Engineering at the University of Delaware. He is the recipient of the 2008 American Automatic Control Council's Control Engineering Practice Award, the ISA's Donald P. Eckman Education Award, the Slocomb Excellence in Teaching Award, and was elected into the US National Academy of Engineering in 2012.
")

item = Item.create(title: "Conduction of Heat in Solids Edition 2", price: 127.95, img: "http://img2.imagesbn.com/p/9780198533689_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0198533683", published: "April 1986", publisher: "Oxford University Press, USA", author: "H. S. Carslaw,Horatio S. Carslaw,J. C. Jaeger", overview: "
                    
This classic account describes the known exact solutions of problems of heat flow, with detailed discussion of all the most important boundary value problems.

                ")
item = Item.create(title: "Boundary Value Problems and Singular Pseudo-Differential Operators Edition 1", price: 350.00, img: "http://img2.imagesbn.com/p/9780471975571_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0471975575", published: "April 1998", publisher: "Wiley", author: "Bert-Wolfgang Schulze,Schultz", overview: "
This book covers the analysis of pseudo-differential operators on manifolds with conical points and edges. The standard singular integral operators on the half-axis as well as boundary value problems on smooth manifolds are treated as particular cone and wedge theories. It features a self-contained presentation of the cone pseudo-differential calculus; a general method for pseudo-differential analysis on manifolds with edges for arbitrary model cones in spaces with discrete and continuous asymptotics; the presentation of the algebra of boundary value problems with the transmission property, obtained as a modification of the general wedge theory; and a new exposition of the pseudo-differential calculus with operator-valued symbols, based on twisted homogeneity as well as on parameter-dependent theories and reductions of orders.
")
item = Item.create(title: "A First Look at Perturbation Theory Edition 2", price: 11.95, img: "http://img1.imagesbn.com/p/9780486675510_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0486675513", published: "July 1997", publisher: "Dover Publications", author: "James G. Simmonds,Physics,James E. Mann (With)", overview: "
                    Undergraduates in engineering and the physical sciences receive a thorough introduction to perturbation theory in this useful and accessible text. Students discover methods for obtaining an approximate solution of a mathematical problem by exploiting the presence of a small, dimensionless parameter — the smaller the parameter, the more accurate the approximate solution. Knowledge of perturbation theory offers a twofold benefit: approximate solutions often reveal the exact solution's essential dependence on specified parameters; also, some problems resistant to numerical solutions may yield to perturbation methods. In fact, numerical and perturbation methods can be combined in a complementary way.
The text opens with a well-defined treatment of finding the roots of polynomials whose coefficients contain a small parameter. Proceeding to differential equations, the authors explain many techniques for handling perturbations that reorder the equations or involve an unbounded independent variable. Two disparate practical problems that can be solved efficiently with perturbation methods conclude the volume.
Written in an informal style that moves from specific examples to general principles, this elementary text emphasizes the \"why\" along with the \"how\"; prerequisites include a knowledge of one-variable calculus and ordinary differential equations. This newly revised second edition features an additional appendix concerning the approximate evaluation of integrals.


                ")
item = Item.create(title: "Self-Organized Criticality in Earth Systems Edition 1", price: 209.00, img: "http://img1.imagesbn.com/p/9783642077906_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "3642077900", published: "December 2010", publisher: "Springer Berlin Heidelberg", author: "Stefan Hergarten", overview: "
                    Self-organized criticality (SOC) has become a magic word in various scientific disciplines; it provides a framework for understanding complexity and scale invariance in systems showing irregular fluctuations. In the first 10 years after Per Bak and his co-workers presented their seminal idea, more than 2000 papers on this topic appeared. Seismology has been a field in earth sciences where the SOC concept has already deepened the understanding, but there seem to be much more examples in earth sciences where applying the SOC concept may be fruitful. After introducing the reader into the basics of fractals, chaos and SOC, the book presents established and new applications of SOC in earth sciences, namely earthquakes, forest fires, landslides and drainage networks.


                ")
item = Item.create(title: "Interactions: Mathematics, Physics and Philosophy, 1860-1930 Edition 1", price: 219.00, img: "http://img1.imagesbn.com/p/9789048173068_p0_v3_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "904817306", published: "November 2010", publisher: "Springer Netherlands", author: "Vincent F. Hendricks (Editor),Klaus F. Jorgensen (Editor),Jesper Lutzen (Editor),Stig A. Pedersen (Editor)", overview: "
                    The main theme of this anthology is the unique interaction between mathematics, physics and philosophy during the beginning of the 20th century. In this book, ten renowned philosopher-historians probe insightfully into key conceptual questions of pre-quantum mathematical physics. The result is a diverse yet thematically focused compilation of first class papers on mathematics, physics and philosophy, and a source-book on the interaction between them.


                ")
item = Item.create(title: "Self-Organized Criticality in Earth Systems Edition 1", price: 209.00, img: "http://img1.imagesbn.com/p/9783540434528_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "3540434526", published: "August 2002", publisher: "Springer Berlin Heidelberg", author: "Stefan Hergarten", overview: "
                    Self-organized criticality (SOC) has become a magic word in various scientific disciplines; it provides a framework for understanding complexity and scale invariance in systems showing irregular fluctuations. In the first 10 years after Per Bak and his co-workers presented their seminal idea, more than 2000 papers on this topic appeared. Seismology has been a field in earth sciences where the SOC concept has already deepened the understanding, but there seem to be much more examples in earth sciences where applying the SOC concept may be fruitful. After introducing the reader into the basics of fractals, chaos and SOC, the book presents established and new applications of SOC in earth sciences, namely earthquakes, forest fires, landslides and drainage networks. 

                ")
item = Item.create(title: "Interactions: Mathematics, Physics and Philosophy, 1860-1930 Edition 1", price: 219.00, img: "http://img1.imagesbn.com/p/9781402051944_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1402051948", published: "February 2007", publisher: "Springer Netherlands", author: "Vincent F. Hendricks (Editor),Klaus F. Jorgensen (Editor),Jesper Lutzen (Editor),Stig A. Pedersen (Editor),Stig Andur Pedersen (Editor)", overview: "
                    The main theme of this anthology is the unique interaction between mathematics, physics and philosophy during the beginning of the 20th century. In this book, ten renowned philosopher-historians probe insightfully into key conceptual questions of pre-quantum mathematical physics. The result is a diverse yet thematically focused compilation of first class papers on mathematics, physics and philosophy, and a source-book on the interaction between them.


                ")
item = Item.create(title: "Introduction to Partial Differential Equations and Hilbert Space Methods Edition 3", price: 19.95, img: "http://img2.imagesbn.com/p/9780486612713_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0486612716", published: "July 1997", publisher: "Dover Publications", author: "Karl E. Gustafson,Perry Ed. Gustafson", overview: "
                    This volume offers an excellent undergraduate-level introduction to the main topics, methods, and applications of partial differential equations.
Chapter 1 presents a full introduction to partial differential equations and Fourier series as related to applied mathematics. Chapter 2 begins with a more comprehensive look at the principal method for solving partial differential equations — the separation of variables — and then more fully develops that approach in the contexts of Hilbert space and numerical methods. Chapter 3 includes an expanded treatment of first-order systems, a short introduction to computational methods, and aspects of topical research on the partial differential equations of fluid dynamics.
With over 600 problems and exercises, along with explanations, examples, and a comprehensive section of answers, hints, and solutions, this superb, easy-to-use text is ideal for a one-semester or full-year course. It will also provide the mathematically inclined layperson with a stimulating review of the subject's essentials.


                ")
item = Item.create(title: "Thinking About Equations: A Practical Guide for Developing Mathematical Intuitionin the Physical Sciences and Engineering Edition 1", price: 72.95, img: "http://img1.imagesbn.com/p/9780470186206_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0470186208", published: "July 2009", publisher: "Wiley", author: "Matt A. Bernstein,William A. Friedman", overview: "
                    An accessible guide to developing intuition and skills for solving mathematical problems in the physical sciences and engineering
Equations play a central role in problem solving across various fields of study. Understanding what an equation means is an essential step toward forming an effective strategy to solve it, and it also lays the foundation for a more successful and fulfilling work experience. Thinking About Equations provides an accessible guide to developing an intuitive understanding of mathematical methods and, at the same time, presents a number of practical mathematical tools for successfully solving problems that arise in engineering and the physical sciences.
Equations form the basis for nearly all numerical solutions, and the authors illustrate how a firm understanding of problem solving can lead to improved strategies for computational approaches. Eight succinct chapters provide thorough topical coverage, including:
Approximation and estimation
Isolating important variables
Generalization and special cases
Dimensional analysis and scaling
Pictorial methods and graphical solutions
Symmetry to simplify equations
Each chapter contains a general discussion that is integrated with worked-out problems from various fields of study, including physics, engineering, applied mathematics, and physical chemistry. These examples illustrate the mathematical concepts and techniques that are frequently encountered when solving problems. To accelerate learning, the worked example problems are grouped by the equation-related concepts that they illustrate as opposed to subfields within science and mathematics, as in conventional treatments. In addition, each problem is accompanied by a comprehensive solution, explanation, and commentary, and numerous exercises at the end of each chapter provide an opportunity to test comprehension.
Requiring only a working knowledge of basic calculus and introductory physics, Thinking About Equations is an excellent supplement for courses in engineering and the physical sciences at the upper-undergraduate and graduate levels. It is also a valuable reference for researchers, practitioners, and educators in all branches of engineering, physics, chemistry, biophysics, and other related fields who encounter mathematical problems in their day-to-day work.


                ")
item = Item.create(title: "Fractals and Chaos: The Mandelbrot Set and Beyond Edition 1", price: 89.99, img: "http://img1.imagesbn.com/p/9781441918970_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1441918973", published: "November 2010", publisher: "Springer New York", author: "Benoit Mandelbrot,C.J.G. Evertsz (With),M.C. Gutzwiller (With),P.W. Jones (Foreword )", overview: "
                    Just 23 years ago Benoit Mandelbrot published his famous picture of the Mandelbrot set, but that picture has changed our view of the mathematical and physical universe. In this text, Mandelbrot offers 25 papers from the past 25 years, many related to the famous inkblot figure. Of historical interest are some early images of this fractal object produced with a crude dot-matrix printer. The text includes some items not previously published.


                ")
item = Item.create(title: "Latent Class And Discrete Latent Trait Models Edition 1", price: 108.00, img: "http://img2.imagesbn.com/p/9780803974333_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0803974337", published: "April 1996", publisher: "SAGE Publications", author: "Ton Heinen", overview: "
                    The standard latent class model. It has been popular among social scientists as an instrument for data reduction, as a flexible tool for analyzing structural relationships between categorical variables, and as a natural extension of the log-linear model in order to take measurement error into account. What, however, are the similarities and differences between the latent class model and latent trait models? Through a careful examination of these issues, author Ton Heinen explores such topics as how to estimate the parameters of latent class analysis models as well as the methods for model selection and ways to examine the correspondence between discrete latent trait models and certain restricted latent class models. In addition, he reviews log-linear models, latent trait models, and a number of restricted latent class models in detail as well as for the estimation of parameters for these models. Readers who would like to see how the estimation of the parameters in latent trait models plays a role in the correspondence between latent class and latent trait models will find Latent Class and Discrete Latent Trait Models a fascinating read. 

                        Incl. local independence/log-linear models & latent class analysis/latent class measurement models/latent trait models

                    
                ")
item = Item.create(title: "Random Fluctuations and Pattern Growth: Experiments and Models Edition 1", price: 169.00, img: "http://img2.imagesbn.com/p/9780792300731_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0792300734", published: "July 2008", publisher: "Springer Netherlands", author: "Harry Eugene Stanley (Editor),N. Ostrowsky (Editor)", overview: "• Contents •.- Course 1: Random Fluctuations and Transport.- Some Themes and Common Tools.- Structure, Elasticity and Thermal Properties of Silica Networks.- Anomalous Diffusion and Fractons in Disordered Structures.- Fractons in Real Fractals.- Anomalous Transport in Disordered Structures: Effect of Additional Disorder.- Information Exponents for Transport in Regular Lattices and Fractals.- Anomalous Transport in Random Linear Structures.- Course 2: Random Growth Patterns: Aggregation.- Morphological Transitions in Pattern Growth Phenomena.- Visualization and Characterization of Microparticle Growth Patterns.- Origin of Fractal Roughness in Synthetic and Natural Materials.- Electrodeposition.- Course 3: Random Fluctuations in Fluid Systems.- Flow Patterns in Porous Media.- Viscous Fingering in a Circular Geometry.- Construction of a Radial Hele-Shaw Cell.- Growth and Viscous Fingers on Percolating Porous Media.- Structure of Miscible and Immiscible Displacement Fronts in Porous Media.- Dynamics of Invasion Percolation.- Course 4: Random Fluctuations in Liquid Crystals.- Directional Solidification of Liquid Crystals.- Interfacial Instabilities of Condensed Phase Domains in Lipid Monolayers.- Pattern Formation of Molecules Adsorbing on Lipid Monolayers.- Course 5: Random Fluctuations in “Solid” Materials.- to Dense Branching Morphology.- The Material Factors Leading to Dense Branching Morphology in Al:Ge Thin Films.- Theoretical Aspects of Polycrystalline Pattern Growth in Al/Ge Films.- Pattern Formation in Dendritic Solidification.- Relaxation of Excitations in Porous Solids.- Soap Bubbles—A Simple Model System for Solids.- Course 6: Fracture of Disordered Solids.- to Modern Ideas on Fracture Patterns.- Rupture in Random Media.- Fracture Experiments on Monolayers of Microspheres.- Simple Models for Colloidal Aggregation, Dielectric Breakdown and Mechanical Breakdown Patterns.- Dielectric Breakdown Patterns with a Growth Probability Threshold.- Course 7: Fluctuation Phenomena in Membranes and Random Surfaces.- The Statistical Mechanics of Crumpled Membranes.- Fluctuations in Fluid and Hexatic Membranes.- Unbinding Transition and Mutual Adhesion in General of DGDG Membranes.- Scaling Properties of Interfaces and Membranes.- Surfactants in Solution: An Experimental Tool to Study Fluctuating Surfaces.- Course 8: Convection, Turbulence and Multifractals.- to Convection.- Onset of Convection.- Waves and Plumes in Thermal Convection.- An Introduction to Multifractal Distribution Functions.- Multifractals in Convection and Aggregation.- Multifractal Analysis of Sedimentary Rocks.- Phase Transition on DLA.- Course 9: Random Fluctuations and Complex Systems.- Disordered Patterns in Deterministic Growth.- 1/f Versus 1/f? Noise.- A Simple Model of Molecular Evolution.- Scale Invariant Spacial and Temporal Fluctuations in Complex Systems.- The Upper Critical Dimension and—-Expansion for Self-Organized Critical Phenomena.- Self-Organized Criticality and the Origin of Fractal Growth.- Finite Lifetime Effects in Models of Epidemics.- to Droplet Growth Processes: Simulations, Theory and Experiments.- List of Participants.

")
item = Item.create(title: "Modern Real and Complex Analysis Edition 1", price: 202.00, img: "http://img1.imagesbn.com/p/9780471107156_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0471107158", published: "May 1995", publisher: "Wiley", author: "Bernard R. Gelbaum,Gelbaum", overview: "
                    Using a contemporary approach and a lively style, Gelbaum combines real and complex analysis, covering all major topics. He discusses topology in three ways: via open sets, nets and filters. Features a detailed exploration of the link between measure as derived from a Daniell functional and classical Lebesgue-Caratheodory measure. Includes complete definitions of all mathematical concepts as well as numerous exercises and illustrations.

                ")
item = Item.create(title: "Measure and Integral: Volume 1 Edition 1", price: 89.95, img: "http://img2.imagesbn.com/p/9780387966335_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0387966331", published: "December 1987", publisher: "Springer New York", author: "John L. Kelley,T.P. Srinivasan,T. P. Srinivasan", overview: "
                    This book is a systematic exposition of the theory of measure and integration. It is intendend for students, and also as a reference work. The body of the text can be read by a student with a firm background in analysis, whereas the supplements treat more advanced topics, and require somewhat more maturity. Although the results given here are the standard ones, the authors have taken a new approach, systematically exploiting the concepts of -ring and -simplicity.

                ")
item = Item.create(title: "Fractals and Chaos in Geology and Geophysics Edition 2", price: 106.00, img: "http://img1.imagesbn.com/p/9780521567336_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0521567335", published: "February 2007", publisher: "Cambridge University Press", author: "Donald L. Turcotte", overview: "
                    Now in a greatly expanded second edition, this book relates fractals and chaos to a variety of geological and geophysical applications and introduces the fundamental concepts of fractal geometry and chaotic dynamics. In this new edition, Turcotte expands coverage of self-organized criticality and includes statistics and time series to provide a broad background for the reader. Topics include drainage networks and erosion, floods, earthquakes, mineral and petroleum resources, fragmentation, mantle convection, and magnetic field generation. The author introduces all concepts at the lowest possible level of mathematics consistent with their understanding, so that the reader requires only a background in basic physics and mathematics. He includes problems for the reader to solve. This book will appeal to a broad range of readers interested in complex natural phenomena.


                ")
item = Item.create(title: "Toward Consilience: The Bioneurological Basis of Behavior, Thought, Experience, and Language Edition 1", price: 199.00, img: "http://img1.imagesbn.com/p/9780306464362_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0306464365", published: "January 2001", publisher: "Springer US", author: "Gerald A. Cory Jr.,Gerald A. Cory Jr", overview: "
                    This book is a comprehensive effort to establish a framework for consilience - the unification of the natural and social sciences. Grounded in physics, molecular biology, and evolutionary neuroscience, Toward Consilience seeks to identify and trace the organic brain algorithms which, when replicated in our neural architecture, shape our human thought, behavior, and language. Drawing on the work of Edward O. Wilson, Paul MacLean, and others, Dr. Corey presents a significant and thought-provoking effort at understanding what makes us human.


                ")
item = Item.create(title: "Mathematics for Engineers and Scientists Edition 6", price: 87.95, img: "http://img1.imagesbn.com/p/9781584884880_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1584884886", published: "August 2004", publisher: "Taylor & Francis", author: "Alan Jeffrey", overview: "
                    Since its original publication in 1969, Mathematics for Engineers and Scientists has built a solid foundation in mathematics for legions of undergraduate science and engineering students. It continues to do so, but as the influence of computers has grown and syllabi have evolved, once again the time has come for a new edition.
Thoroughly revised to meet the needs of today's curricula, Mathematics for Engineers and Scientists, Sixth Edition covers all of the topics typically introduced to first- or second-year engineering students, from number systems, functions, and vectors to series, differential equations, and numerical analysis. Among the most significant revisions to this edition are:
Simplified presentation of many topics and expanded explanations that further ease the comprehension of incoming engineering students
A new chapter on double integrals
Many more exercises, applications, and worked examples
A new chapter introducing the MATLAB and Maple software packages
Although designed as a textbook with problem sets in each chapter and selected answers at the end of the book, Mathematics for Engineers and Scientists, Sixth Edition serves equally well as a supplemental text and for self-study. The author strongly encourages readers to make use of computer algebra software, to experiment with it, and to learn more about mathematical functions and the operations that it can perform.


                ")
item = Item.create(title: "Degeneration of Abelian Varieties Edition 1", price: 139.00, img: "http://img2.imagesbn.com/p/9783642080883_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "364208088", published: "December 2010", publisher: "Springer Berlin Heidelberg", author: "Gerd Faltings,Ching-Li Chai", overview: "
                    A new and complete treatment of semi-abelian degenerations of abelian varieties, and their application to the construction of arithmetic compactifications of Siegel moduli space, with most of the results being published for the first time. Highlights of the book include a classification of semi-abelian schemes, construction of the toroidal and the minimal compactification over the integers, heights for abelian varieties over number fields, and Eichler integrals in several variables, together with a new approach to Siegel modular forms. A valuable source of reference for researchers and graduate students interested in algebraic geometry, Shimura varieties or diophantine geometry.


                ")
item = Item.create(title: "Image-Based Fractal Description of Microstructures Edition 1", price: 215.00, img: "http://img1.imagesbn.com/p/9781441953704_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1441953701", published: "December 2010", publisher: "Springer US", author: "J.M. Li,Li Lu,Man On Lai,B. Ralph", overview: "
                    Fractal analysis has rapidly become an important field in materials science and engineering with broad applications to theoretical analysis and quantitative description of microstructures of materials. Fractal methods have thus far shown great potential in engineering applications in quantitative microscopic analysis of materials using commercial microscopes.
This book attempts to introduce the fundamentals and the basis methods of fractal description of microstructures in combination with digital imaging and computer technologies. Basic concepts are given in the form of mathematical expressions. Detailed algorithms in practical applications are also provided. Fractal measurement, error analysis and fractal description of cluster growth, thin films and surfaces are emphasized in this book.
Image-Based Fractal Description of Microstructures provides a comprehensive approach to materials characterization by fractal from theory to application.


                ")
item = Item.create(title: "Algorithmic Learning in a Random World Edition 1", price: 149.00, img: "http://img1.imagesbn.com/p/9781441934710_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1441934715", published: "October 2010", publisher: "Springer US", author: "Vladimir Vovk,Alex Gammerman,Glenn Shafer", overview: "
                    Algorithmic Learning in a Random World describes recent theoretical and experimental developments in building computable approximations to Kolmogorov's algorithmic notion of randomness. Based on these approximations, a new set of machine learning algorithms have been developed that can be used to make predictions and to estimate their confidence and credibility in high-dimensional spaces under the usual assumption that the data are independent and identically distributed (assumption of randomness). Another aim of this unique monograph is to outline some limits of predictions: The approach based on algorithmic theory of randomness allows for the proof of impossibility of prediction in certain situations. The book describes how several important machine learning problems, such as density estimation in high-dimensional spaces, cannot be solved if the only assumption is randomness.


                ")
item = Item.create(title: "A Guided Tour of Mathematical Methods: For the Physical Sciences Edition 2", price: 90.00, img: "http://img1.imagesbn.com/p/9780521834926_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0521834929", published: "August 2004", publisher: "Cambridge University Press", author: "Roel Snieder", overview: "
                    This second edition of A Guided Tour of Mathematical Methods provides a comprehensive tour of the mathematical knowledge and techniques that are needed by students in this area. In contrast to more traditional textbooks, all the material is presented in the form of problems. Within these problems the basic mathematical theory and its physical applications are well integrated. The mathematical insights that the student acquires are therefore driven by their physical insight. Topics that are covered include vector calculus, linear algebra, Fourier analysis, scale analysis, complex integration, Green's functions, normal modes, tensor calculus, and perturbation theory. The second edition contains new chapters on dimensional analysis, variational calculus, and the asymptotic evaluation of integrals. This book can be used by undergraduates and lower-level graduate students in the physical sciences. It can serve as a stand-alone text, or as a source of problems and examples to complement other textbooks.

                ")
item = Item.create(title: "Mathematical Methods for Physics and Engineering: A Comprehensive Guide Edition 3", price: 106.00, img: "http://img1.imagesbn.com/p/9780521679718_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0521679710", published: "February 2006", publisher: "Cambridge University Press", author: "K. F. Riley,M. P. Hobson,S. J. Bence", overview: "
                    All physical scientists and engineers need mathematical tools in their everyday work. This book takes the student from the level of starting college or university to the end of the most mathematical of science courses. It also provides a valuable reference for active researchers in physics, engineering, chemistry, applied mathematics and earth science.Throughout the text, the ph ysical relevance of the mathematics is constantly reinforced, and numerous physical worked examples are included. In this way, it provides scientists who need to use the tools of mathematics for practical purposes with a single, comprehensive textbook.

                ")
item = Item.create(title: "Global Methods for Combinatorial Isoperimetric Problems Edition 1", price: 112.00, img: "http://img2.imagesbn.com/p/9780521832687_p0_v1_s600.gif", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0521832683", published: "January 2004", publisher: "Cambridge University Press", author: "L. H. Harper,B. Bollobas (Contribution ),W. Fulton (Contribution ),A. Katok (Contribution ),F. Kirwan (Contribution )", overview: "
                    The study of combinatorial isoperimetric problems exploits similarities between discrete optimization problems and the classical continuous setting. Based on his many years of teaching experience, Larry Harper focuses on global methods of problem solving. His text will enable graduate students and researchers to quickly reach the most current state of research in this topic. Harper includes numerous worked examples, exercises and material about applications to computer science.


                ")
item = Item.create(title: "The Mountain Pass Theorem: Variants, Generalizations and Some Applications Edition 1", price: 165.00, img: "http://img1.imagesbn.com/p/9780521827218_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0521827213", published: "September 2003", publisher: "Cambridge University Press", author: "Youssef Jabri,G. -C Rota (Editor),Joussef Jabri", overview: "
                    Joussef Jabri presents min-max methods through a comprehensive study of the different faces of the celebrated Mountain Pass Theorem (MPT) of Ambrosetti and Rabinowitz. Jabri clarifies the extensions and variants of the MPT in a complete and unified way and covers standard topics: the classical and dual MPT; second-order information from PS sequences; symmetry and topological index theory; perturbations from symmetry; convexity and more. He also covers the non-smooth MPT; the geometrically constrained MPT; numerical approaches to the MPT; and even more exotic variants. A bibliography and detailed index are also included.


                ")
item = Item.create(title: "Basic Training in Mathematics: A Fitness Program for Science Students Edition 1", price: 124.00, img: "http://img1.imagesbn.com/p/9780306450358_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0306450356", published: "June 1995", publisher: "Springer US", author: "R. Shankar", overview: "
                    Based on course material used by the author at Yale University, this practical text addresses the widening gap found between the mathematics required for upper-level courses in the physical sciences and the knowledge of incoming students. This superb book offers students an excellent opportunity to strengthen their mathematical skills by solving various problems in differential calculus. By covering material in its simplest form, students can look forward to a smooth entry into any course in the physical sciences.


                ")
item = Item.create(title: "Compactness Methods for Nonlinear Evolutions Edition 2", price: 159.95, img: "http://img1.imagesbn.com/p/9780582248724_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0582248728", published: "July 1995", publisher: "Taylor & Francis", author: "Ioan I Vrabie", overview: "
                    This monograph provides a self-contained and comprehensive account of the most significant existence results obtained over the
past two decades referring to some remarkable classes of ill-posed problems governed by non-accretive operators. All the results are derived from several compactness arguments, due mainly to the author, and are suitably illustrated by examples arising from various concrete problems - for example, nonlinear diffusion, heat conduction in materials with memory, fluid dynamics, and vibrations of a string with memory. Reference is made to optimal control theory in order to emphasize the degree of applicability of abstract compactness methods. Special attention is paid to multivalued perturbations of m-accretive operators; this case is analyzed under appropriate assumptions in order to allow the use of the general results in the study of some specific problems of great practical interest: reaction-diffusion and closed loop systems. Some biographical comments and open problems are also included. This new edition contains a number of improvements, corrections and insertions which both simplify and update the material. The book will be of interest to graduate students and specialists working in abstract evolution equations, partial differential equations, reaction-diffusion systems and ill-posed problems. A knowledge of topology, functional analysis and ordinary differential equations to undergraduate level is assumed.


                ")
item = Item.create(title: "Random Fluctuations and Pattern Growth: Experiments and Models Edition 1", price: 349.00, img: "http://img1.imagesbn.com/p/9780792300724_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0792300726", published: "December 1988", publisher: "Springer Netherlands", author: "Harry Eugene Stanley (Editor),N. Ostrowsky,H. E. Stanley (Editor)", overview: "• Contents •.- Course 1: Random Fluctuations and Transport.- Some Themes and Common Tools.- Structure, Elasticity and Thermal Properties of Silica Networks.- Anomalous Diffusion and Fractons in Disordered Structures.- Fractons in Real Fractals.- Anomalous Transport in Disordered Structures: Effect of Additional Disorder.- Information Exponents for Transport in Regular Lattices and Fractals.- Anomalous Transport in Random Linear Structures.- Course 2: Random Growth Patterns: Aggregation.- Morphological Transitions in Pattern Growth Phenomena.- Visualization and Characterization of Microparticle Growth Patterns.- Origin of Fractal Roughness in Synthetic and Natural Materials.- Electrodeposition.- Course 3: Random Fluctuations in Fluid Systems.- Flow Patterns in Porous Media.- Viscous Fingering in a Circular Geometry.- Construction of a Radial Hele-Shaw Cell.- Growth and Viscous Fingers on Percolating Porous Media.- Structure of Miscible and Immiscible Displacement Fronts in Porous Media.- Dynamics of Invasion Percolation.- Course 4: Random Fluctuations in Liquid Crystals.- Directional Solidification of Liquid Crystals.- Interfacial Instabilities of Condensed Phase Domains in Lipid Monolayers.- Pattern Formation of Molecules Adsorbing on Lipid Monolayers.- Course 5: Random Fluctuations in “Solid” Materials.- to Dense Branching Morphology.- The Material Factors Leading to Dense Branching Morphology in Al:Ge Thin Films.- Theoretical Aspects of Polycrystalline Pattern Growth in Al/Ge Films.- Pattern Formation in Dendritic Solidification.- Relaxation of Excitations in Porous Solids.- Soap Bubbles—A Simple Model System for Solids.- Course 6: Fracture of Disordered Solids.- to Modern Ideas on Fracture Patterns.- Rupture in Random Media.- Fracture Experiments on Monolayers of Microspheres.- Simple Models for Colloidal Aggregation, Dielectric Breakdown and Mechanical Breakdown Patterns.- Dielectric Breakdown Patterns with a Growth Probability Threshold.- Course 7: Fluctuation Phenomena in Membranes and Random Surfaces.- The Statistical Mechanics of Crumpled Membranes.- Fluctuations in Fluid and Hexatic Membranes.- Unbinding Transition and Mutual Adhesion in General of DGDG Membranes.- Scaling Properties of Interfaces and Membranes.- Surfactants in Solution: An Experimental Tool to Study Fluctuating Surfaces.- Course 8: Convection, Turbulence and Multifractals.- to Convection.- Onset of Convection.- Waves and Plumes in Thermal Convection.- An Introduction to Multifractal Distribution Functions.- Multifractals in Convection and Aggregation.- Multifractal Analysis of Sedimentary Rocks.- Phase Transition on DLA.- Course 9: Random Fluctuations and Complex Systems.- Disordered Patterns in Deterministic Growth.- 1/f Versus 1/f? Noise.- A Simple Model of Molecular Evolution.- Scale Invariant Spacial and Temporal Fluctuations in Complex Systems.- The Upper Critical Dimension and—-Expansion for Self-Organized Critical Phenomena.- Self-Organized Criticality and the Origin of Fractal Growth.- Finite Lifetime Effects in Models of Epidemics.- to Droplet Growth Processes: Simulations, Theory and Experiments.- List of Participants.

")
item = Item.create(title: "Toward an Anthropology of Graphing: Semiotic and Activity-Theoretic Perspectives Edition 1", price: 209.00, img: "http://img1.imagesbn.com/p/9781402013744_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1402013744", published: "July 2003", publisher: "Springer Netherlands", author: "W.M. Roth,W. M. Roth", overview: "
                    This volume presents the results of several studies involving scientists and technicians. The author describes and analyses the interpretation scientists volunteered given graphs that had been culled from an introductory course and textbook in ecology. He next reports on graph usage in three different workplaces based on his ethnographic research among scientists and technicians.


                ")
item = Item.create(title: "Toward an Anthropology of Graphing: Semiotic and Activity-Theoretic Perspectives Edition 1", price: 84.95, img: "http://img1.imagesbn.com/p/9781402013768_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1402013760", published: "July 2003", publisher: "Springer Netherlands", author: "W.M. Roth", overview: "
                    This volume presents the results of several studies involving scientists and technicians. The author describes and analyses the interpretation scientists volunteered given graphs that had been culled from an introductory course and textbook in ecology. He next reports on graph usage in three different workplaces based on his ethnographic research among scientists and technicians.


                ")
item = Item.create(title: "Fourier and Laplace Transforms Edition 1", price: 95.00, img: "http://img2.imagesbn.com/p/9780521534413_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0521534410", published: "August 2003", publisher: "Cambridge University Press", author: "R. J. Beerends,H. G. ter Morsche,J. C. van den Berg,E. M. van de Vrie", overview: "
                    This textbook describes in detail the various Fourier and Laplace transforms that are used to analyze problems in mathematics, the natural sciences and engineering. These transforms decompose complicated signals into elementary signals, and are widely used across the spectrum of science and engineering. Applications include electrical and mechanical networks, heat conduction and filters. In contrast with other books, continuous and discrete transforms are given equal coverage.


                ")
item = Item.create(title: "Brownian Motion and Stochastic Calculus Edition 2", price: 64.95, img: "http://img1.imagesbn.com/p/9780387976556_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0387976558", published: "August 1991", publisher: "Springer New York", author: "Ioannis Karatzas,Steven Shreve", overview: "
                    A graduate-course text, written for readers familiar with measure-theoretic probability and discrete-time processes, wishing to explore shastic processes in continuous time. The vehicle chosen for this exposition is Brownian motion, which is presented as the canonical example of both a martingale and a Markov process with continuous paths. In this context, the theory of shastic integration and shastic calculus is developed, illustrated by results concerning representations of martingales and change of measure on Wiener space, which in turn permit a presentation of recent advances in financial economics. The book contains a detailed discussion of weak and strong solutions of shastic differential equations and a study of local time for semimartingales, with special emphasis on the theory of Brownian local time. The whole is backed by a large number of problems and exercises.


                ")
item = Item.create(title: "Variational Inequalities and Flow in Porous Media Edition 1", price: 109.00, img: "http://img2.imagesbn.com/p/9780387960029_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0387960023", published: "June 1984", publisher: "Springer New York", author: "M. Chipot", overview: "1. Abstract Existence and Uniqueness Results for Solutions of Variational Inequalities.- 2. Examples and Applications.- 3. The Obstacle Problems: A Regularity Theory.- 4. The Dam Problem.- References.

")
item = Item.create(title: "Convergence Structures and Applications to Functional Analysis Edition 1", price: 119.00, img: "http://img1.imagesbn.com/p/9781402005664_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1402005660", published: "March 2002", publisher: "Springer Netherlands", author: "R. Beattie,Heinz-Peter Butzmann", overview: "
                    This text offers a rigorous introduction into the theory and methods of convergence spaces and gives concrete applications to the problems of functional analysis. While there are a few books dealing with convergence spaces and a great many on functional analysis, there are none with this particular focus.
The book demonstrates the applicability of convergence structures to functional analysis. Highlighted here is the role of continuous convergence, a convergence structure particularly appropriate to function spaces. It is shown to provide an excellent dual structure for both topological groups and topological vector spaces.
Readers will find the text rich in examples. Of interest, as well, are the many filter and ultrafilter proofs which often provide a fresh perspective on a well-known result.
Audience: This text will be of interest to researchers in functional analysis, analysis and topology as well as anyone already working with convergence spaces. It is appropriate for senior undergraduate or graduate level students with some background in analysis and topology.


                ")
item = Item.create(title: "Advanced Basic Meta-Analysis Edition 1", price: 60.00, img: "http://img1.imagesbn.com/p/9780805805024_p0_v1_s600.gif", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0805805028", published: "January 1989", publisher: "Taylor & Francis", author: "Brian Mullen,Thomas Mullen", overview: "
                    In response to the growing emphasis on precision in the summarization and integration of research literature, Advanced BASIC Meta-Analysis presents an overview of strategies, techniques, and procedures used in meta-analysis.
The book and software provide an integrated and comprehensive combination of meta-analytic tools for the statistical integration of independent study results. Advanced BASIC Meta-Analysis has three distinct goals:
• to provide a clear and user-friendly introduction to the procedures and rules of effective meta-analytic integration;
• to present the implicit assumptions and strategies that guide successful meta-analytic integrations; and
• to develop a meta-analytic database management system that allows users to create, modify, and update a database, including the relevant statistical information and predictors, for a given research domain.
The companion software system allows users to perform a full complement of meta-analytic statistical functions with the speed and flexibility of a database management system. It can also construct a wide array of meta-analytic graphic displays. This text and software package serves as a useful introduction to the quantitative assessment of research domains for those new to meta-analyses. It is also a valuable sourcebook for those who have already conducted meta-analyses.


                ")
item = Item.create(title: "Physics of Fractal Operators Edition 1", price: 134.00, img: "http://img2.imagesbn.com/p/9781441930545_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "144193054", published: "May 2011", publisher: "Springer New York", author: "Bruce West,Mauro Bologna,Paolo Grigolini", overview: "
                    This text describes how fractal phenomena, both deterministic and random, change over time, using the fractional calculus. The intent is to identify those characteristics of complex physical phenomena that require fractional derivatives or fractional integrals to describe how the process changes over time. The discussion emphasizes the properties of physical phenomena whose evolution is best described using the fractional calculus, such as systems with long-range spatial interactions or long-time memory.
In many cases, classic analytic function theory cannot serve for modeling complex phenomena; \"Fractal Operators\" shows how classes of less familiar functions, such as fractals, can serve as useful models in such cases. Because fractal functions, such as the Weierstrass function (long known not to have a derivative), do in fact have fractional derivatives, they can be cast as solutions to fractional differential equations. The traditional techniques for solving differential equations, including Fourier and Laplace transforms as well as Green's functions, can be generalized to fractional derivatives.
Fractal Operators addresses a general strategy for understanding wave propagation through random media, the nonlinear response of complex materials, and the fluctuations of various forms of transport in heterogeneous materials. This strategy builds on traditional approaches and explains why the historical techniques fail as phenomena become more and more complicated.


                ")
item = Item.create(title: "Light Scattering Media Optics Edition 3", price: 239.00, img: "http://img1.imagesbn.com/p/9783540211846_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "3540211845", published: "April 2005", publisher: "Springer Berlin Heidelberg", author: "Alexander A. Kokhanovsky", overview: "
                    The theory of the scattering of light by small particles is very important in a wide range of applications in atmospheric physics and atmospheric optics, ocean optics, remote sensing, astronomy and astrophysics and biological optics. This book summarises current knowledge of the optical properties of single small particles and natural light scattering media such as snow, clouds, foam aerosols etc. The book considers both single and multiple light scattering regimes, together with light scattering and radiative transfer in close-packed media. The third edition incorporates new findings in the area of light scattering media optics in an updated version of the text.


                ")
item = Item.create(title: "Dynamics of Evolutionary Equations Edition 1", price: 179.00, img: "http://img1.imagesbn.com/p/9781441931184_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "144193118", published: "December 2010", publisher: "Springer New York", author: "George R. Sell,Yuncheng You", overview: "
                    The theory and applications of infinite dimensional dynamical systems have attracted the attention of scientists for quite some time. This book serves as an entrée for scholars beginning their journey into the world of dynamical systems, especially infinite dimensional spaces. The main approach involves the theory of evolutionary equations.


                ")
item = Item.create(title: "Algorithmic Learning in a Random World Edition 1", price: 149.00, img: "http://img1.imagesbn.com/p/9780387001524_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0387001522", published: "March 2005", publisher: "Springer US", author: "Vladimir Vovk,Alex Gammerman,Glenn Shafer", overview: "
                    Algorithmic Learning in a Random World describes recent theoretical and experimental developments in building computable approximations to Kolmogorov's algorithmic notion of randomness. Based on these approximations, a new set of machine learning algorithms have been developed that can be used to make predictions and to estimate their confidence and credibility in high-dimensional spaces under the usual assumption that the data are independent and identically distributed (assumption of randomness). Another aim of this unique monograph is to outline some limits of predictions: The approach based on algorithmic theory of randomness allows for the proof of impossibility of prediction in certain situations. The book describes how several important machine learning problems, such as density estimation in high-dimensional spaces, cannot be solved if the only assumption is randomness.


                ")
item = Item.create(title: "Sampling Theory in Fourier and Signal Analysis: Volume 1: Foundations Edition 1", price: 150.00, img: "http://img1.imagesbn.com/p/9780198596998_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0198596995", published: "August 1996", publisher: "Oxford University Press, USA", author: "John Rowland Higgins,Higgins", overview: "
                    
With much material not previously found in book form, this book fills a gap by discussing the equivalence of signal functions with their sets of values taken at discreet points comprehensively and on a firm mathematical ground. The wide variety of topics begins with an introduction to the main ideas and background material on Fourier analysis and Hilbert spaces and their bases. Other chapters discuss sampling of Bernstein and Paley-Wiener spaces; Kramer's Lemma and its application to eigenvalue problems; contour integral methods including a proof of the equivalence of the sampling theory; the Poisson summation formula and Cauchy's integral formula; optimal regular, irregular, multi-channel, multi-band and multi-dimensional sampling; and Campbell's generalized sampling theorem. Mathematicians, physicists, and communications engineers will welcome the scope of information found here.

                ")
item = Item.create(title: "Image-Based Fractal Description of Microstructures Edition 1", price: 215.00, img: "http://img1.imagesbn.com/p/9781402075070_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1402075073", published: "July 2003", publisher: "Springer US", author: "J.M. Li,Li Lu,Man On Lai,B. Ralph", overview: "
                    Fractal analysis has rapidly become an important field in materials science and engineering with broad applications to theoretical analysis and quantitative description of microstructures of materials. Fractal methods have thus far shown great potential in engineering applications in quantitative microscopic analysis of materials using commercial microscopes.
This book attempts to introduce the fundamentals and the basis methods of fractal description of microstructures in combination with digital imaging and computer technologies. Basic concepts are given in the form of mathematical expressions. Detailed algorithms in practical applications are also provided. Fractal measurement, error analysis and fractal description of cluster growth, thin films and surfaces are emphasized in this book.
Image-Based Fractal Description of Microstructures provides a comprehensive approach to materials characterization by fractal from theory to application.


                ")
item = Item.create(title: "Measure and Integration: An Advanced Course in Basic Procedures and Applications Edition 1", price: 119.00, img: "http://img1.imagesbn.com/p/9783540618584_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "3540618589", published: "November 2011", publisher: "Springer Berlin Heidelberg", author: "Heinz Konig,Heinz Kanig", overview: "
                    This book aims at restructuring some fundamentals in measure and integration theory. It centers around the ubiquitous task to produce appropriate contents and measures from more primitive data like elementary contents and elementary integrals. It develops the new approach started around 1970 by Topsoe and others into a systematic theory. The theory is much more powerful than the traditional means and has striking implications all over measure theory and beyond.


                ")
item = Item.create(title: "Floquet Theory for Partial Differential Equations Edition 1", price: 129.00, img: "http://img2.imagesbn.com/p/9783764329013_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "3764329017", published: "December 2008", publisher: "Birkhauser Basel", author: "P.A. Kuchment", overview: "
                    This monograph provides the first survey of Floquet theory for partial differential equations with periodic coefficients. The author investigates, among others, hypoelliptic, parabolic, elliptic and Schrödinger equations, and boundary value problems arising in applications. In particular, results are given about completeness of the set of Floquet solutions, Floquet expansions of arbitrary solutions, the distribution of Floquet exponents and quasimomentums, the solvability of nonhomogeneous equations, the existence of decreasing or bounded solutions, and the structure of the spectrum of periodic operators. Many of the results discussed here have been available only in research papers until now. The role of the Floquet-Lyapunov theory for ordinary differential equations is well known, but for partial differential equations an analog of this theory has been developed only recently. This theory is of great importance for the quantum theory of solids, the theory of wave guides, scattering theory and other fields of mathematical and theoretical physics. Some chapters devoted to operator theory may be of particular interest to specialists in complex analysis and functional analysis.


                ")
item = Item.create(title: "Subspace Methods for System Identification Edition 1", price: 239.00, img: "http://img1.imagesbn.com/p/9781852339814_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "1852339810", published: "October 2005", publisher: "Springer London", author: "Tohru Katayama", overview: "
                    System identification provides methods for the sensible approximation of real systems using a model set based on experimental input and output data. Tohru Katayama sets out an in-depth introduction to subspace methods for system identification in discrete-time linear systems thoroughly augmented with advanced and novel results. The text is structured into three parts.

                ")
item = Item.create(title: "Sampling Algorithms Edition 1", price: 169.00, img: "http://img1.imagesbn.com/p/9780387308142_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0387308148", published: "March 2006", publisher: "Springer New York", author: "Yves Tille", overview: "
                    Over the last few decades, important progresses in the methods of sampling have been achieved. This book draws up an inventory of new methods that can be useful for selecting samples. Forty-six sampling methods are described in the framework of general theory. The algorithms are described rigorously, which allows implementing directly the described methods. This book is aimed at experienced statisticians who are familiar with the theory of survey sampling.About the Author:
Yves Tille is a professor at the University of Neuchatel, Switzerland


                ")
item = Item.create(title: "Degeneration of Abelian Varieties Edition 1", price: 139.00, img: "http://img2.imagesbn.com/p/9783540520153_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "3540520155", published: "December 1990", publisher: "Springer Berlin Heidelberg", author: "Gerd Faltings,Ching-Li Chai", overview: "
                    A new and complete treatment of semi-abelian degenerations of abelian varieties, and their application to the construction of arithmetic compactifications of Siegel moduli space, with most of the results being published for the first time. Highlights of the book include a classification of semi-abelian schemes, construction of the toroidal and the minimal compactification over the integers, heights for abelian varieties over number fields, and Eichler integrals in several variables, together with a new approach to Siegel modular forms. A valuable source of reference for researchers and graduate students interested in algebraic geometry, Shimura varieties or diophantine geometry.


                ")
item = Item.create(title: "Classification and Regression Trees Edition 1", price: 104.95, img: "http://img1.imagesbn.com/p/9780412048418_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0412048418", published: "January 1984", publisher: "Taylor & Francis", author: "Leo Breiman,Jerome Friedman,Charles J. Stone,R.A. Olshen", overview: "
                    The methodology used to construct tree structured rules is the focus of this monograph. Unlike many other statistical procedures, which moved from pencil and paper to calculators, this text's use of trees was unthinkable before computers. Both the practical and theoretical sides have been developed in the authors'study of tree methods. Classification and Regression Trees reflects these two sides, covering the use of trees as a data analysis method, and in a more mathematical framework, proving some of their fundamental properties.


                ")
item = Item.create(title: "Stochastic Methods: A Handbook for the Natural and Social Sciences Edition 4", price: 109.00, img: "http://img2.imagesbn.com/p/9783540707127_p0_v3_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "3540707123", published: "February 2009", publisher: "Springer Berlin Heidelberg", author: "Crispin Gardiner", overview: "
                    This fourth edition of the classic text \"A Handbook of Shastic Methods\" has been significantly augmented, thoroughly revised, and restructured to accomodate the new material within a systematic logical framework. This new edition adheres the original aim: \"to make available in simple language and deductive form, the many formulae and methods that can be found in the literature on shastic methods.\"
A new chapter on the applications of shastic methods in finance provides an introduction to this field using the same simple kind of language as the other parts of the book. This chapter also includes an introduction to Lévy processes, which have found to be very useful in simulating financial systems where more accuracy is required than is available from simple Brownian motion models. New material is also provided on the approach to the white noise limit, on the applications of Poisson representation methods to population dynamics, and on several other applications of shastic methods.
From the reviews of previous editions
\"Extremely well written and informative... clear, complete, and fairly rigorous treatment of a larger number of very basic concepts in shastic theory.\" (Journal of Quantum Electronics)
\"A first class book.\" (Optica Acta)
\"Ideal for people who need a clear introduction to shastic mathematics and their applications in physical sciencesÃ¢â‚¬Â¦ an excellent self study and reference book.\" (Quantnotes.com)
\"This well-established volume takes a supreme position [among the many books on the subject].. This extremely valuable contribution to the field of applied shastic methods can be recommended to graduate students, researchers, and university teachers.\" (Optimization)


                ")
item = Item.create(title: "I: Functional Analysis: Volume 1 Edition 2", price: 195.00, img: "http://img1.imagesbn.com/p/9780125850506_p0_v3_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0125850506", published: "January 1981", publisher: "Elsevier Science", author: "Michael Reed", overview: "
                    This book is the first of a multivolume series devoted to an exposition of functional analysis methods in modern mathematical physics. It describes the fundamental principles of functional analysis and is essentially self-contained, although there are occasional references to later volumes. We have included a few applications when we thought that they would provide motivation for the reader. Later volumes describe various advanced topics in functional analysis and give numerous applications in classical physics, modern physics, and partial differential equations.

                        Audience: Graduate and advanced undergraduate students studying mathematics.

                    
                ")
item = Item.create(title: "Violence in Europe: Historical and Contemporary Perspectives Edition 1", price: 59.99, img: "http://img1.imagesbn.com/p/9780387097046_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "038709704", published: "October 2008", publisher: "Springer New York", author: "Sophie Body-Gendrot (Editor),Pieter Spierenburg (Editor)", overview: "
                    Taking the sociocultural long view, Violence in Europe analyzes the prevalence and role of violence-from street crime to terrorist attacks, homicide to genocide-in the evolution of human and national behavior. The editors and 14 colleagues in history, anthropology, sociology, and psychology focus on Northern and Western Europe, examining centuries of violent phenomena, from the cultural logic of the Middle Ages to today's soccer riots and security alerts. The contributors' examination of social constructions (honor codes, class and gender roles) and public ambivalence (acceptance, abhorrence, fascination) regarding violence sheds needed light on current dynamics in law enforcement, political systems, and what many have termed \"the civilization of violence.\"
Findings from Britain, France, Ireland, Belgium, and Scandinavia explore: The paradoxes of ethnic violence and insider/outsider thinking in an increasingly multicultural world, Trends in interpersonal violence during wartime and peacetime, The gendering of violence, from early French marital laws to London's underground nightlife, The growth of cities: modernization, conflict, aggression, Modern prevention and surveillance strategies: effective solutions, complicating the problem, or some middle ground?
Reflecting innovative methods of research and interpretation, Violence in Europe is thought-provoking and instructive for researchers and students in psychology and criminology. And with the mounting global presence of violence today, this is reading with profound implications for the future.


                ")
item = Item.create(title: "Fractals and Multifractals in Ecology and Aquatic Science Edition 1", price: 98.95, img: "http://img2.imagesbn.com/p/9780849327827_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0849327822", published: "October 2009", publisher: "CRC Press", author: "Laurent Seuront", overview: "
                    Ecologists sometimes have a less-than-rigorous background in quantitative methods, yet research within this broad field is becoming increasingly mathematical. Written in a step-by-step fashion, Fractals and Multifractals in Ecology and Aquatic Science provides scientists with a basic understanding of fractals and multifractals and the techniques for utilizing them when analyzing ecological phenomenon.
With illustrations, tables, and graphs on virtually every page – several in color – this book is a comprehensive source of state-of-the-art ecological scaling and multiscaling methods at temporal and spatial scales, respectfully ranging from seconds to months and from millimeters to thousands of kilometers. It illustrates most of the data analysis techniques with real case studies often based on original findings. It also incorporates descriptions of current and new numerical techniques to analyze and deepen understanding of ecological situations and their solutions.
Includes a Wealth of Applications and Examples
This book also includes nonlinear analysis techniques and the application of concepts from chaos theory to problems of spatial and temporal patterns in ecological systems. Unlike other books on the subject, Fractals and Multifractals in Ecology and Aquatic Science is readily accessible to researchers in a variety of fields, such as microbiology, biology, ecology, hydrology, geology, oceanography, social sciences, and finance, regardless of their mathematical backgrounds. This volume demystifies the mathematical methods, many of which are often regarded as too complex, and allows the reader to access new and promising concepts, procedures, and related results.


                ")
item = Item.create(title: "A Student's Guide to Fourier Transforms: With Applications in Physics and Engineering Edition 2", price: 36.99, img: "http://img1.imagesbn.com/p/9780521004282_p0_v1_s600.jpg", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0521004284", published: "September 2002", publisher: "Cambridge University Press", author: "J. F. James", overview: "
                    The book assumes no previous knowledge of the subject, and will be invaluable to students of physics, electrical and electronic engineering, and computer science.

                ")
item = Item.create(title: "Classical Complex Analysis Edition 1", price: 224.95, img: "http://img1.imagesbn.com/p/9780867204940_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "086720494", published: "April 1996", publisher: "Jones & Bartlett Learning", author: "Liang-shin Hahn,Bernard Epstein", overview: "
                    Classic Complex Analysis is a text that has been developed over decades of teaching with an enthusiastic student reception. The first half of the book focuses on the core material. An early chapter on power series gives the reader concrete examples of analytic functions and a review of calculus. Mobius transformations are presented with emphasis on the geometric aspect, and the Cauchy theorem is covered in the classical manner. The remaining chapters provide an elegant and solid overview of special topics such as Entire and Meromorphic Functions, Analytic Continuation, Normal Families, Conformal Mapping, and Harmonic Functions.

                ")
item = Item.create(title: "Violence in Europe: Historical and Contemporary Perspectives Edition 1", price: 189.00, img: "http://img2.imagesbn.com/p/9780387745077_p0_v2_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0387745076", published: "December 2007", publisher: "Springer New York", author: "Sophie Body-Gendrot,Pieter Spierenburg", overview: "
                    Taking the sociocultural long view, Violence in Europe analyzes the prevalence and role of violence-from street crime to terrorist attacks, homicide to genocide-in the evolution of human and national behavior. The editors and 14 colleagues in history, anthropology, sociology, and psychology focus on Northern and Western Europe, examining centuries of violent phenomena, from the cultural logic of the Middle Ages to today's soccer riots and security alerts. The contributors' examination of social constructions (honor codes, class and gender roles) and public ambivalence (acceptance, abhorrence, fascination) regarding violence sheds needed light on current dynamics in law enforcement, political systems, and what many have termed \"the civilization of violence.\"
Findings from Britain, France, Ireland, Belgium, and Scandinavia explore: The paradoxes of ethnic violence and insider/outsider thinking in an increasingly multicultural world, Trends in interpersonal violence during wartime and peacetime, The gendering of violence, from early French marital laws to London's underground nightlife, The growth of cities: modernization, conflict, aggression, Modern prevention and surveillance strategies: effective solutions, complicating the problem, or some middle ground?
Reflecting innovative methods of research and interpretation, Violence in Europe is thought-provoking and instructive for researchers and students in psychology and criminology. And with the mounting global presence of violence today, this is reading with profound implications for the future.


                ")
item = Item.create(title: "Textbook of Treatment Algorithms in Psychopharmacology Edition 1", price: 303.00, img: "http://img2.imagesbn.com/p/9780471981091_p0_v1_s600.JPG", cat_id: 5)
ItemInfo.create(item_id: item.id, isbn: "0471981095", published: "August 1999", publisher: "Wiley, John & Sons, Incorporated", author: "Jan Fawcett (Editor),Dan J. Stein (Editor),Kenneth O. Jobson (Editor)", overview: "
                    Psychopharmacology is the study of drugs used to treat psychiatric disorders. This textbook looks at the use of clinical algorithms in relation to clinical psychopharmacology, especially the nature and current use of algorithms, and their future potential for the medical community.

                        The book contains black-and-white illustrations.

                    
                ")
