source 'https://rubygems.org'

####BACKEND
gem 'rails', '4.0.2'
gem 'bcrypt'
gem 'jbuilder', '~> 1.2'



####FRONT END
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'


group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :production do
  gem 'pg'
end

group :development do 
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'faker'
  gem 'sqlite3'
end
