item = Item.create(title: "Elementary Linear Algebra (Student Solution Manual) Edition 7", price: 34.75, img: "http://img2.imagesbn.com/p/9780471306221_p0_v1_s600.gif", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0471306223", published: "January 1994", publisher: "Wiley, John & Sons, Incorporated", author: "Howard Anton", overview: "
                    Presents the fundamentals of linear algebra in the clearest possible way, examining basic ideas by means of computational examples and geometrical interpretation. This substantial revision includes greater focus on relationships between concepts, smoother transition to abstraction, early exposure to linear transformations and eigenvalues, more emphasize on visualization, new material on least squares and QR-decomposition and a greater number of proofs. Exercise sets begin with routine drill problems, progress to problems with more substance and conclude with theoretical problems.

                ")
item = Item.create(title: "Elementary Linear Algebra Edition 7", price: 89.75, img: "http://img1.imagesbn.com/p/9780471587422_p0_v1_s600.gif", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0471587427", published: "December 1993", publisher: "Wiley, John & Sons, Incorporated", author: "Howard Anton", overview: "
                    Presents the fundamentals of linear algebra in the clearest possible way, examining basic ideas by means of computational examples and geometrical interpretation. This substantial revision includes greater focus on relationships between concepts, smoother transition to abstraction, early exposure to linear transformations and eigenvalues, more emphasize on visualization, new material on least squares and QR-decomposition and a greater number of proofs. Exercise sets begin with routine drill problems, progress to problems with more substance and conclude with theoretical problems.

                ")
item = Item.create(title: "Algebra Edition 1", price: 32.95, img: "http://img2.imagesbn.com/p/9780817636777_p0_v2_s600.JPG", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0817636773", published: "July 2003", publisher: "Birkhauser Verlag", author: "I.M. Gelfand,Alexander Shen,A. Shen (With)", overview: "
                    The need for improved mathematics education at the high school and college levels has never been more apparent than in the 1990's. As early as the 1960's, I.M. Gelfand and his colleagues in the USSR thought hard about this same question and developed a style for presenting basic mathematics in a clear and simple form that engaged the curiosity and intellectual interest of thousands of high school and college students. These same ideas, this development, are available in the following books to any student who is willing to read, to be stimulated, and to learn. 
 \"Algebra\" is an elementary algebra text from one of the leading mathematicians of the world -- a major contribution to the teaching of the very first high school level course in a centuries old topic -- refreshed by the author's inimitable pedagogical style and deep understanding of mathematics and how it is taught and learned. 
This text has been adopted at: 
Holyoke Community College, Holyoke, MA * University of Illinois in Chicago, Chicago, IL * University of Chicago, Chicago, IL * California State University, Hayward, CA * Georgia Southwestern College, Americus, GA * Carey College, Hattiesburg, MS

                ")
item = Item.create(title: "Strings, Conformal Fields, and M-Theory Edition 2", price: 159.00, img: "http://img1.imagesbn.com/p/9780387988924_p0_v2_s600.JPG", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0387988920", published: "December 1999", publisher: "Springer New York", author: "Michio Kaku", overview: "
                    Building on the foundations laid in his Introduction to Superstrings and M Theory, Professor Kaku discusses such topics as the classification of conformal string theories, knot theory, the Yang-Baxter relation, quantum groups, and the insights into 11-dimensional strings recently obtained from M-theory. New chapters discuss such topics as Seiberg-Witten theory, M theory and duality, and D-branes. Throughout, the author conveys the vitality of the current research and places readers at its forefront. Several chapters reviewing the fundamentals of string theory, making the presentation of the material self-contained while keeping overlap with the earlier book to a minimum.


                ")
item = Item.create(title: "The Maple Book Edition 1", price: 75.95, img: "http://img2.imagesbn.com/p/9781584882329_p0_v2_s600.JPG", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "1584882328", published: "November 2001", publisher: "Taylor & Francis", author: "Frank Garvan", overview: "
                    Maple is a very powerful computer algebra system used by students, educators, mathematicians, statisticians, scientists, and engineers for doing numerical and symbolic computations. Greatly expanded and updated from the author's MAPLE V Primer, The MAPLE Book offers extensive coverage of the latest version of this outstanding software package, MAPLE 7.0
The MAPLE Book serves both as an introduction to Maple and as a reference. Organized according to level and subject area of mathematics, it first covers the basics of high school algebra and graphing, continues with calculus and differential equations then moves on to more advanced topics,
 such as linear algebra, vector calculus, complex analysis, special functions, group theory, number theory and combinatorics. The MAPLE Book includes a tutorial for learning the Maple programming language. Once readers have learned how to program, they will appreciate the real power of Maple.
The convenient format and straightforward style of The MAPLE Book let users proceed at their own pace, practice with the examples,
 experiment with graphics, and learn new functions as they need them. All of the Maple commands used in the book are available on the Internet, as are links to various other files referred to in the book. Whatever your level of expertise, you'll want to keep The MAPLE Book next to your computer.


                ")
item = Item.create(title: "Five Equations That Changed the World: The Power and Poetry of Mathematics Edition 1", price: 16.00, img: "http://img2.imagesbn.com/p/9780786881871_p0_v1_s600.JPG", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0786881879", published: "September 1996", publisher: "Hyperion", author: "Michael Guillen,Guillen", overview: "
                    A Publishers Weekly best book of 1995! 
Dr. Michael Guillen, known to millions as the science editor of ABC's Good Morning America, tells the fascinating stories behind five mathematical equations.
As a regular contributor to daytime's most popular morning news show and an instructor at Harvard University, Dr. Michael Guillen has earned the respect of millions as a clear and entertaining guide to the exhilarating world of science and mathematics.
Now Dr. Guillen unravels the equations that have led to the inventions and events that characterize the modern world, one of which -- Albert Einstein's famous energy equation, E=mc2 -- enabled the creation of the nuclear bomb. Also revealed are the mathematical foundations for the moon landing, airplane travel, the electric generator -- and even life itself.
Praised by Publishers Weekly as \"a wholly accessible, beautifully written exploration of the potent mathematical imagination,\" and named a Best Nonfiction Book of 1995, the stories behind The Five Equations That Changed the World, as told by Dr. Guillen, are not only chronicles of science, but also gripping dramas of jealousy, fame, war, and discovery.


                        From the popular science editor of ABC's Good Morning America, this is the story behind five mathematical equations that have shaped the modern world. As told by Dr. Guillen, the stories behind the creation of these formulas are not only chronicles of science, but also gripping dramas of jealousy, fame, war, and discovery. Author media.

                    
                ")
item = Item.create(title: "Physics: AlgebraTrig (with CD-ROM) Edition 3", price: 336.95, img: "http://img1.imagesbn.com/p/9780534377298_p0_v1_s600.jpg", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0534377297", published: "July 2002", publisher: "Cengage Learning", author: "Eugene Hecht", overview: "
                    In Hecht's groundbreaking book, you'll find real-life applications, an unparalleled art and photography program, a presentation that anticipates students' questions, and an approach that emphasizes contemporary physics while interweaving historical perspectives. Hecht's coverage of classical physics is clear and insightful. He shows students how 21st-century physics illuminates the classical topics of each chapter, adding excitement to the subject matter. Over 1,300 illustrations make it possible for students to visualize a diversity of physical phenomena. Many of these are multi-frame, sequential drawings allowing students to comprehend the temporal unfolding of complex events. A selection of sketch art teaches students how to create problem-solving diagrams. This new edition of the text was designed to aggressively address the issue of problem solving for students (guided by contemporary physics education research). To this end Hecht has provided not only his approach to the five-step problem-solving framework but also a wide range of new problems and solutions specifically designed to build student capability and confidence.


                ")
item = Item.create(title: "Essential Algebra for Chemistry Students Edition 2", price: 52.95, img: "http://img2.imagesbn.com/p/9780495013273_p0_v1_s600.jpg", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0495013277", published: "January 2005", publisher: "Cengage Learning", author: "David W. Ball,Gabriela C. Weaver,Paul M. Treichel,John C. Kotz", overview: "
                    Available packaged with any CENGAGE textbook, this short book is intended for students who lack confidence and/or competency in their essential mathematics skills necessary to survive in general chemistry. Each chapter focuses on a specific type of skill and has worked-out examples to show how these skills translate to chemical problem solving. This book is also available for students to purchase separately at www.CENGAGEbrain.com.


                ")
item = Item.create(title: "Linear Multivariable Control Edition 1", price: 730.00, img: "http://img2.imagesbn.com/p/9780471928591_p0_v1_s600.jpg", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0471928593", published: "September 1991", publisher: "Wiley", author: "A. I. G. Vardulakis,Vardulakis", overview: "
                    Details the basic theory of polynomial and fractional representation methods for algebraic analysis and synthesis of linear multivariable control systems. It also serves as a self-contained treatise of the mathematical theory so that results and techniques of the &'grave;state space approaches'' for regular and singular systems appear as special cases of a general theory covering the wider class of PMDs of linear systems. Among the topics covered are: real rational vector spaces and rational matrices, pole and zero structure of rational matrices at infinity, proper and omega stable rational fuctions and matrices.


                ")
item = Item.create(title: "Conformal Field Theory Edition 1", price: 175.00, img: "http://img2.imagesbn.com/p/9780387947853_p0_v1_s600.JPG", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "038794785", published: "September 2010", publisher: "Springer New York", author: "Philippe Francesco,Pierre Mathieu,David Senechal", overview: "
                    Filling an important gap in the literature, this comprehensive text develops conformal field theory from first principles. The treatment is self-contained, pedagogical, and exhaustive, and includes a great deal of background material on quantum field theory, statistical mechanics, Lie algebras and affine Lie algebras. The many exercises, with a wide spectrum of difficulty and subjects, complement and in many cases extend the text. The text is thus not only an excellent tool for classroom teaching but also for individual study. Intended primarily for graduate students and researchers in theoretical high-energy physics, mathematical physics, condensed matter theory, statistical physics, the book will also be of interest in other areas of theoretical physics and mathematics. It will prepare the reader for original research in this very active field of theoretical and mathematical physics.

                ")
item = Item.create(title: "Algorithmic Algebra Edition 1", price: 89.95, img: "http://img1.imagesbn.com/p/9780387940908_p0_v1_s600.jpg", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0387940901", published: "September 1993", publisher: "Springer New York", author: "Bhubaneswar Mishra", overview: "
                    Algorithmic Algebra studies some of the main algorithmic tools of computer algebra, covering such topics as Gröbner bases, characteristic sets, resultants and semialgebraic sets. The main purpose of the book is to acquaint advanced undergraduate and graduate students in computer science, engineering and mathematics with the algorithmic ideas in computer algebra so that they could do research in computational algebra or understand the algorithms underlying many popular symbolic computational systems: Mathematica, Maple or Axiom, for instance. Also, researchers in robotics, solid modeling, computational geometry and automated theorem proving community may find it useful as symbolic algebraic techniques have begun to play an important role in these areas. The book, while being self-contained, is written at an advanced level and deals with the subject at an appropriate depth. The book is accessible to computer science students with no previous algebraic training. Some mathematical readers, on the other hand, may find it interesting to see how algorithmic constructions have been used to provide fresh proofs for some classical theorems. The book also contains a large number of exercises with solutions to selected exercises, thus making it ideal as a textbook or for self-study.

                ")
item = Item.create(title: "Clifford Algebras and Spinors Edition 2", price: 124.00, img: "http://img2.imagesbn.com/p/9780521005517_p0_v1_s600.jpg", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0521005515", published: "June 2006", publisher: "Cambridge University Press", author: "Pertti Lounesto,J. W. S. Cassels (Editor),N. J. Hitchin (Editor)", overview: "
                    This second edition of a popular and unique introduction to Clifford algebras and spinors has three new chapters. The beginning chapters cover the basics: vectors, complex numbers and quaternions are introduced with an eye on Clifford algebras. The next chapters, which will also interest physicists, include treatments of the quantum mechanics of the electron, electromagnetism and special relativity. A new classification of spinors is introduced, based on bilinear covariants of physical observables. This reveals a new class of spinors, residing among the Weyl, Majorana and Dirac spinors. Scalar products of spinors are categorized by involutory anti-automorphisms of Clifford algebras. This leads to the chessboard of automorphism groups of scalar products of spinors. On the algebraic side, Brauer/Wall groups and Witt rings are discussed, and on the analytic, Cauchy's integral formula is generalized to higher dimensions.


                ")
item = Item.create(title: "Earth Algebra, College Algebra with Applications to Environmental Issues Edition 2", price: 93.00, img: "http://img1.imagesbn.com/p/9780321015976_p0_v1_s600.gif", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0321015975", published: "August 1998", publisher: "Addison-Wesley", author: "Christopher Schaufele,Stanle Sims,Marlene Sims,Nancy Zumoff,Stanley Sims", overview: "
                    This college algebra text focuses on modeling (primarily by curve fitting) real data concerning environmental issues, decision making, reading, writing, and oral reporting. Students work in small groups with graphing calculators or appropriate technology.

                ")
item = Item.create(title: "Why Americans Hate Welfare: Race, Media, and the Politics of Antipoverty Policy Edition 1", price: 21.00, img: "http://img2.imagesbn.com/p/9780226293653_p0_v1_s600.jpg", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0226293653", published: "October 2000", publisher: "University of Chicago Press", author: "MartinGilens", overview: "
                    
Tackling one of the most volatile issues in contemporary politics, Martin Gilens's work punctures myths and misconceptions about welfare policy, public opinion, and the role of the media in both. Why Americans Hate Welfare shows that the public's views on welfare are a complex mixture of cynicism and compassion; misinformed and racially charged, they nevertheless reflect both a distrust of welfare recipients and a desire to do more to help the \"deserving\" poor.
\"With one out of five children currently living in poverty and more than 100,000 families with children now homeless, Gilens's book is must reading if you want to understand how the mainstream media have helped justify, and even produce, this state of affairs.\" —Susan Douglas, The Progressive
\"Gilens\'s well-written and logically developed argument deserves to be taken seriously.\" —Choice
\"A provocative analysis of American attitudes towards 'welfare.'. . . [Gilens] shows how racial stereotypes, not white self-interest or anti-statism, lie at the root of opposition to welfare programs.\" -Library Journal


                ")
item = Item.create(title: "Selected Papers on Algebra and Topology by Garrett Birkhoff Edition 1", price: 409.00, img: "http://img2.imagesbn.com/p/9780817631147_p0_v1_s600.jpg", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0817631143", published: "January 1987", publisher: "Birkhauser Verlag", author: "J.S. Oliveira (Editor),G.-C. Rota (Editor)", overview: "I. Lattices.- [3] On the Combination of Subalgebras.- [3a] Note on the Paper “On the Combination of Subalgebras”.- [4] Applications of Lattice Algebra.- [6] On the Lattice Theory of Ideals.- [7] Ideals in Algebraic Rings.- [12] Combinatorial Relations in Projective Geometries.- [16] Abstract Linear Dependence and Lattices.- [21] The Logic of Quantum Mechanics (with J. von Neumann).- [36] A Characterization of Boolean Algebras (with M. Ward).- [40] Neutral Elements in General Lattices.- [51] Distributive Postulates for Systems Like Boolean Algebras (with G. D. Birkhoff).- [54] A Ternary Operation in Distributive Lattices (with S. A. Kiss).- II. Universal Algebra.- [15] On the Structure of Abstract Algebras.- [47] Subdirect Unions in Universal Algebra.- [49] Universal Algebra.- [154] Heterogeneous Algebras (with J. D. Lipson).- [174] Universal Algebra and Automata (with J. D. Lipson).- [179] Note on Universal Topological Algebra.- III. Topology.- [8] The Topology of Transformation-Sets.- [24] Moore-Smith Convergence in General Topology.- [25] The Meaning of Completeness.- [28] An Extended Arithmetic.- [29] Rings of Sets.- [43] Generalized Arithmetic.- [58] Representations of Lattices by Sets (with O. Frink, Jr.).- [118] A New Interval Topology for Dually Directed Sets.- IV. Lie Groups and Lie Algebras.- [19] On the Order of Groups of Automorphisms (with P. Hall).- [20] A Note on Topological Groups.- [22] Lie Groups Simply Isomorphic with No Linear Group.- [26] Continuous Groups and Linear Spaces.- [27] Representability of Lie Algebras and Lie Groups by Matrices.- [32] Analytical Groups.- [60] Representation of Jordan and Lie Algebras (with P. M. Whitman).- V. Lattice-Ordered Algebraic Structures.- [33] Dependent Probabilities and Spaces (L).- [42] Lattice-Ordered Groups.- [48] Lattice-Ordered Lie Groups.- [91] Lattice-Ordered Rings (with R. S. Pierce).- VI. History of Algebra.- [160] Current Trends in Algebra.- [169] The Role of Modern Algebra in Computing.- [182a] The Rise of Modern Algebra to 1936.- [182b] The Rise of Modern Algebra, 1936 to 1950.- Permissions.

")
item = Item.create(title: "Why Americans Hate Welfare: Race, Media, and the Politics of Antipoverty Policy Edition 1", price: 25.00, img: "http://img1.imagesbn.com/p/9780226293646_p0_v1_s600.gif", cat_id: 2, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0226293645", published: "May 1999", publisher: "University of Chicago Press", author: "MartinGilens", overview: "
                    Drawing on surveys of public attitudes and analyses of more than forty years of television and newsmagazine stories on poverty, Gilens demonstrates how public opposition to welfare is fed by a potent combination of racial stereotypes and misinformation about the true nature of America's poor. But white Americans don't oppose welfare simply because they think it benefits blacks; rather, they think it benefits \"undeserving\" blacks who would rather live off the government than work, a perception powerfully fueled by the media's negative coverage of the black poor. The public's views on welfare, Gilens shows, are a complex mixture of cynicism and compassion; misinformed and racially charged, they nevertheless reflect both a distrust of welfare recipients and a desire to do more to help the \"deserving\" poor.

                ")
