item = Item.create(title: "Discourse on Method, Optics, Geometry, and Meteorology Edition 1", price: 19.00, img: "http://img2.imagesbn.com/p/9780872205673_p0_v1_s600.jpg", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0872205673", published: "March 2001", publisher: "Hackett Publishing Company, Inc.", author: "Rene Descartes,Paul J. Olscamp", overview: "BooknewsDescartes (1596-1650) intended the four books to be read together, the three on specific subjects demonstrating the methods he describes, but they have generally been studied separately since their first publication. Olscamp (Western Washington U.) brings them back together in a corrected version of his 1963 translation, published by Bobbs- Merrill. Annotation c. Book News, Inc., Portland, OR (booknews.com)

")
item = Item.create(title: "In Our Own Image: Personal Symmetry in Discovery Edition 1", price: 89.99, img: "http://img2.imagesbn.com/p/9780306460913_p0_v2_s600.JPG", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0306460912", published: "January 2000", publisher: "Springer US", author: "Istvan Hargittai,Magdolna Hargittai,Magdolna Hargittai (Joint Author)", overview: "
                    This book inquires into the nature of scientific discovery. The focus is on six personalities and six scientific fields: Johannes Kepler and modeling, Buckminster Fuller and molecules, Linus Pauling and helices of biological systems, A. Kitaiigorodskii and packing of shapes, D.J. Bernal and quasicrystals, and Pierre Curie and symmetry breaking. Excerpts from conversations with 40 leading scientists, including 17 Nobel laureates, enliven the discussion. Culture and science blend inseparably in this book and natural curiosity is the only prerequisite to enjoy it. The award winning authors created this book for the interested general public and it is illustrated by striking images.


                ")
item = Item.create(title: "The Geometry Problem Solver : Plane, Solid, Analytic: A Complete Solution Guide to Any Textbook Edition 1", price: 25.95, img: "http://img2.imagesbn.com/p/9780878915101_p0_v1_s600.jpg", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0878915109", published: "January 1998", publisher: "Research & Education Association", author: "The Editors of REA,Ernest Woodward,Research & Education Association", overview: "
                    
 REA’s Problem Solvers is a series of useful, practical, and informative study guides. Each title in the series is complete step-by-step solution guide. The Geometry Problem Solver enables students to solve difficult problems by showing them step-by-step solutions to Geometry problems.
The Problem Solvers cover material ranging from the elementary to the advanced and make excellent review books and textbook companions.
The Geometry Problem Solver is the perfect resource for any class, any exam, and any problem!


                ")
item = Item.create(title: "Reflections on Spacetime: Foundations, Philosophy, History Edition 1", price: 99.00, img: "http://img2.imagesbn.com/p/9789048146123_p0_v3_s600.JPG", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "9048146127", published: "December 2010", publisher: "Springer Netherlands", author: "Ulrich Majer (Editor),Heinz-Juergen Schmidt (Editor)", overview: "
                    This book presents a collection of research papers, written by physicists, philosophers and historians of science who had participated in the Zentrum für interdisziplinäre Forschung (ZiF) during the academic year 1992/93 in order to discuss the nature and structure of spacetime as it is used in general relativity. All contributions focus on unsolved questions, such as the possibility of time machines, referential indeterminacy, the hole problem, and the conventional vs. empirical character of spacetime. These papers having a more historical colour deal with Einstein's view of general covariance and with the epistemological status of space(time) in the works of Carnap, Weyl and Hilbert, all of whom relate their position to Husserl's phenomenology, yet in fundamentally different ways.


                ")
item = Item.create(title: "Further Advances in Twistor Theory: Curved Twistor Spaces Edition 1", price: 164.95, img: "http://img2.imagesbn.com/p/9781584880479_p0_v1_s600.JPG", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "1584880473", published: "March 2001", publisher: "Taylor & Francis", author: "L.J. Mason (Editor),P.Z. Kobak (Editor),L. Hughston (Editor),K. Pulverer (Editor)", overview: "
                    Although twistor theory originated as an approach to the unification of quantum theory and general relativity, twistor correspondences and their generalizations have provided powerful mathematical tools for studying problems in differential geometry, nonlinear equations, and representation theory. At the same time, the theory continues to offer promising new insights into the nature of quantum theory and gravitation.
Further Advances in Twistor Theory, Volume III: Curved Twistor Spaces is actually the fourth in a series of books compiling articles from Twistor Newsletter-a somewhat informal journal published periodically by the Oxford research group of Roger Penrose. Motivated both by questions in differential geometry and by the quest to find a twistor correspondence for general Ricci-flat space times, this volume explores deformed twistor spaces and their applications.
Articles from the world's leading researchers in this field-including Roger Penrose-have been written in an informal, easy-to-read style and arranged in four chapters, each supplemented by a detailed introduction. Collectively, they trace the development of the twistor programme over the last 20 years and provide an overview of its recent advances and current status.


                ")
item = Item.create(title: "Hyperspace: A Scientific Odyssey Through Parallel Universes, Time Warps, and the Tenth Dimension Edition 1", price: 60.00, img: "http://img2.imagesbn.com/p/9780195085143_p0_v1_s600.JPG", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0195085140", published: "March 1994", publisher: "Oxford University Press", author: "Michio Kaku,Robert O'Keefe (Illustrator)", overview: "
                    Are there other dimensions beyond our own? Is time travel possible? Can we change the past? Are there gateways to parallel universes? All of us have pondered such questions, but there was a time when scientists dismissed these notions as outlandish speculations. Not any more. Today, they are the focus of the most intense scientific activity in recent memory. In Hyperspace, Michio Kaku, author of the widely acclaimed Beyond Einstein and a leading theoretical physicist, offers the first book-length tour of the most exciting (and perhaps most bizarre) work in modern physics, work which includes research on the tenth dimension, time warps, black holes, and multiple universes. The theory of hyperspace (or higher dimensional space) - and its newest wrinkle, superstring theory - stand at the center of this revolution, with adherents in every major research laboratory in the world, including several Nobel laureates. Beginning where Hawking's Brief History of Time left off, Kaku paints a vivid portrayal of the breakthroughs now rocking the physics establishment. Why all the excitement? As the author points out, for over half a century, scientists have puzzled over why the basic forces of the cosmos - gravity, electromagnetism, and the strong and weak nuclear forces - require markedly different mathematical descriptions. But if we see these forces as vibrations in a higher dimensional space, their field equations suddenly fit together like pieces in a jigsaw puzzle, perfectly snug, in an elegant, astonishingly simple form. This may thus be our leading candidate for the Theory of Everything. If so, it would be the crowning achievement of 2,000 years of scientific investigation into matter and its forces. Already, the theory has inspired several thousand research papers, and has been the focus of over 200 international conferences. Many leading scientists believe the theory will unlock the deepest secrets of creation and answer some of the most intriguing questions of all

                        Kaku, a physicist, paints a vivid portrait of the groundbreaking theory of hyperspace and its newest wrinkle--superstring theory.

                    
                ")
item = Item.create(title: "Statistical Methods: The Geometric Approach Edition 1", price: 159.00, img: "http://img2.imagesbn.com/p/9780387975177_p0_v2_s600.JPG", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0387975179", published: "May 1991", publisher: "Springer New York", author: "David J. Saville,Graham R. Wood", overview: "
                    A novel exposition of the analysis of variance and regression. The key feature here is that these tools are viewed in their natural mathematical setting - the geometry of finite dimensions. This is because geometry clarifies the basic statistics and unifies the many aspects of analysing variance and regression.


                ")
item = Item.create(title: "The Completeness of Scientific Theories: On the Derivation of Empirical Indicators within a Theoretical Framework: The Case of Physical Geometry Edition 1", price: 279.00, img: "http://img2.imagesbn.com/p/9780792324751_p0_v2_s600.JPG", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0792324757", published: "November 1993", publisher: "Springer Netherlands", author: "Martin Carrier,M. Carrier", overview: "
                    The Completeness of Scientific Theories deals with the role of theories in measurement. Theories are employed in measurements in order to account for the operation of the instruments and to correct the raw data obtained. These observation theories thus guarantee the reliability of measurement procedures. In special cases a theory can be used as its own observation theory. In such cases it is possible, relying on the theory itself, to analyze the measuring procedures associated with theoretical states specified within its framework. This feature is called completeness. The book addresses the assets and liabilities of theories exhibiting this feature.
 Chief among the prima-facie liabilities is a testability problem. If a theory that is supposed to explain certain measurement results at the same time provides the theoretical means necessary for obtaining these results, the threat of circularity arises. Closer investigation reveals that various circularity problems do indeed emerge in complete theories, but that these problems can generally be solved. Some methods for testing and confirming theories are developed and discussed.
 The particulars of complete theories are addressed using a variety of theories from the physical sciences and psychology as examples. The example developed in greatest detail is general relativity theory, which exhibits an outstanding degree of completeness. In this context a new approach to the issue of the conventionality of physical geometry is pursued.
 The book contains the first systematic analysis of completeness; it thus opens up new paths of research.
 For philosophers of science working on problems of confirmation, theory-ladenness of evidence, empirical testability, and space—time philosophy (or students in these areas).


                ")
item = Item.create(title: "Reflections on Spacetime: Foundations, Philosophy, History Edition 1", price: 99.00, img: "http://img1.imagesbn.com/p/9780792337126_p0_v1_s600.JPG", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0792337123", published: "August 1995", publisher: "Springer Netherlands", author: "Ulrich Majer (Editor),Heinz-Juergen Schmidt (Editor)", overview: "
                    This book presents a collection of research papers, written by physicists, philosophers and historians of science who had participated in the Zentrum für interdisziplinäre Forschung (ZiF) during the academic year 1992/93 in order to discuss the nature and structure of spacetime as it is used in general relativity. All contributions focus on unsolved questions, such as the possibility of time machines, referential indeterminacy, the hole problem, and the conventional vs. empirical character of spacetime. These papers having a more historical colour deal with Einstein's view of general covariance and with the epistemological status of space(time) in the works of Carnap, Weyl and Hilbert, all of whom relate their position to Husserl's phenomenology, yet in fundamentally different ways.


                ")
item = Item.create(title: "Differential Geometry: Cartan's Generalization of Klein's Erlangen Program Edition 1", price: 79.95, img: "http://img2.imagesbn.com/p/9780387947327_p0_v1_s600.jpg", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0387947329", published: "June 1997", publisher: "Springer New York", author: "R.W. Sharpe,S.S. Chern", overview: "
                    Cartan geometries were the first examples of connections on a principal bundle. They seem to be almost unknown these days, in spite of the great beauty and conceptual power they confer on geometry. The aim of the present book is to fill the gap in the literature on differential geometry by the missing notion of Cartan connections. Although the author had in mind a book accessible to graduate students, potential readers would also include working differential geometers who would like to know more about what Cartan did, which was to give a notion of "espaces généralisés" (= Cartan geometries) generalizing homogeneous spaces (= Klein geometries) in the same way that Riemannian geometry generalizes Euclidean geometry. In addition, physicists will be interested to see the fully satisfying way in which their gauge theory can be truly regarded as geometry.


                ")
item = Item.create(title: "Combinatorial Convexity and Algebraic Geometry Edition 1", price: 79.95, img: "http://img1.imagesbn.com/p/9780387947556_p0_v1_s600.JPG", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0387947558", published: "October 1996", publisher: "Springer New York", author: "Gunter Ewald,G]nter Ewald,Ga1/4nter Ewald", overview: "
                    This text provides an introduction to the theory of convex polytopes and polyhedral sets, to algebraic geometry and to the fascinating connections between these fields: the theory of toric varieties (or torus embeddings).
The fist part of the book contains an introduction to the theory of polytopes - one of the most important parts of classical geometry in n-dimensional Euclidean space. Since the discussion here is independent of any applications to algebraic geometry, it would also be suitable for a course in geometry. This part also provides large parts of the mathematical background of linear optimization and of the geometrical aspects in Computer Science. The second part introduces toric varieties in an elementary way, building on the concepts of combinatorial geometry introduced in the first part. Many of the general concepts of algebraic geometry arise in this treatment and can be dealt with concretely. This part of the book can thus serve for a one-semester introduction to algebraic geometry, with the first part serving as a reference for combinatorial geometry.


                ")
item = Item.create(title: "Vectors And Tensors In Engineering And Physics Edition 2", price: 58.00, img: "http://img2.imagesbn.com/p/9780813340807_p0_v1_s600.jpg", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0813340802", published: "January 2003", publisher: "Westview Press", author: "Donald Danielson", overview: "
                    Vectors and Tensors in Engineering and Physics develops the calculus of tensor fields and uses this mathematics to model the physical world. This new edition includes expanded derivations and solutions, and new applications. The book provides equations for predicting: the rotations of gyroscopes and other axisymmetric solids, derived from Euler's equations for the motion of rigid bodies; the temperature decays in quenched forgings, derived from the heat equation; the deformed shapes of twisted rods and bent beams, derived from the Navier equations of elasticity; the flow fields in cylindrical pipes, derived from the Navier-Stokes equations of fluid mechanics; the trajectories of celestial objects, derived from both Newton's and Einstein's theories of gravitation; the electromagnetic fields of stationary and moving charged particles, derived from Maxwell's equations; the stress in the skin when it is stretched, derived from the mechanics of curved membranes; the effects of motion and gravitation upon the times of clocks, derived from the special and general theories of relativity. The book also features over 100 illustrations, complete solutions to over 400 examples and problems, Cartesian components, general components, and components-free notations, lists of notations used by other authors, boxes to highlight key equations, historical notes, and an extensive bibliography.

                ")
item = Item.create(title: "Infinite Dimensional Morse Theory and Multiple Solution Problems Edition 1", price: 199.00, img: "http://img2.imagesbn.com/p/9780817634513_p0_v1_s600.jpg", cat_id: 1, clicks: 0, rating: 0)
ItemInfo.create(item_id: item.id, isbn: "0817634517", published: "January 1992", publisher: "Birkhauser Verlag", author: "K.C. Chang,K. C. Chang", overview: "BooknewsChang treats Morse theory as a tool to study multiple solutions to different equations arising in the calculus of variations. Among the topics he covers are basic Morse theory and its various extensions; minimax principles in Morse theory; and applications of semilinear boundary value problems, periodic solutions of Hamiltonian systems, and harmonic maps. In a self-contained appendix, Chang presents Witten's proof of Morse inequalities. Annotation c. Book News, Inc., Portland, OR (booknews.com)

")
